//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mioto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThuCongTy
    {
        public int IDDTC { get; set; }
        public Nullable<int> IDNV { get; set; }
        public Nullable<decimal> DoanhThuNgay { get; set; }
        public Nullable<decimal> DoanhThuTuan { get; set; }
        public Nullable<decimal> DoanhThuThang { get; set; }
        public Nullable<decimal> DoanhThuNam { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
