//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mioto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThueXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonThueXe()
        {
            this.ChiTietDonThueXe = new HashSet<ChiTietDonThueXe>();
            this.ThanhToan = new HashSet<ThanhToan>();
        }
    
        public int IDDT { get; set; }
        public Nullable<int> IDKH { get; set; }
        public string BienSoXe { get; set; }
        public Nullable<int> IDNVXacThuc { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<System.DateTime> BDT { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> IDMGG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonThueXe> ChiTietDonThueXe { get; set; }
        public virtual Xe Xe { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual MaGiamGia MaGiamGia { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToan { get; set; }
    }
}
